### ISSUE TITLE
Largepepsibottle

### ISSUE THREAD

**Issue by De4-DeV** [ArcPh1r3/PaladinMod#12]
dont listen to him its a sun it should stay bright let it blind him

**Comment by GalacticRuler** [comment]
accessibility features that are optional are always a good idea. You want it bright? Leave the config alone. Hell, maybe it could be made brighter with that.

**Comment by De4-DeV** [comment]
Thank you Friend

**Comment by TheTimeSweeper** [comment]
I can agree with this. 
I have no clue how the fuck to go about it but I'll keep it in mind

**Comment by TheTimeSweeper** [comment]
the new cruel sun rework has had the sun's brightness lowered. closing until people see it as an issue again
