### ISSUE TITLE
Cruel Sun Proc? :)

### ISSUE THREAD

**Issue by TheWombat89** [ArcPh1r3/PaladinMod#13]
I know Cruel sun is a meme ability, but making it proc would make it at least playable. Is that something you guys are thinking about doing?

**Comment by TheTimeSweeper** [comment]
"something you guys are thinking"
no thoughts, head empty

jokes aside yeah that sounds good. if this guy ever gets looked at again hopefully this'll be something

**Comment by Keklord-Channel4** [comment]
I would like to know what all the proc coefficients are.

**Comment by TheTimeSweeper** [comment]
new rework have fun
