### ISSUE TITLE
Achievements not working

### ISSUE THREAD

**Issue by ArtyBoi69** [ArcPh1r3/PaladinMod#15]
i was wondering if i could get some help with paladin
i was trying to unlock some of her challenges but it seems they dont work
like i did the 8 lunar items and the her disciple and shiz and none of them unlocked
Was hoping to get some help on this issue

**Comment by JellyJones** [comment]
Issue with the last patch from what I can tell.
https://github.com/risk-of-thunder/R2API/pull/390

**Comment by TheTimeSweeper** [comment]
fixed like 4 months ago lol
