### ISSUE TITLE
Cruel Sun

### ISSUE THREAD

**Issue by SonOfCarX4** [ArcPh1r3/PaladinMod#18]
This isn't really a issue but more of a complaint and I wasn't sure where to write it so I figured here would work. I just started playing the new update and love the new version of the Cruel Sun since it's more viable now, but I did really like the old version. I was wondering if you could add the old version of cruel sun where you can make it spawn super far away along with the current version. It also would be nice to make it do a lot more damage than previously so people still have a reason to use it and maybe you can make it have more of a red color instead of the yellow. It would be completely busted but it would be a super fun ability to use in game. If you can't make this happen, I understand, I just really liked the original concept. Anyways thanks for the best mod on RoR2 by far.

**Comment by TheTimeSweeper** [comment]
thanks for enjoying either version. the legacy version can be re-enabled in config, let me know if there are issues with it
