### ISSUE TITLE
a lot of items are scaled wrong and appear huge

### ISSUE THREAD

**Issue by Mangos02** [ArcPh1r3/PaladinMod#2]
the latest update made most items i get appear extremely huge mostly head items so far

**Comment by GeorgeGedox** [comment]
This applies to any item that's not in vanilla, is there a possibility of hiding unknown items like how other character mods do it?

**Comment by MrWallFlower** [comment]
happened to me on a run, it was the houseplant
![20210123220518_1](https://user-images.githubusercontent.com/47309996/105641672-37ab0100-5e3a-11eb-9dc6-0615c1f72406.jpg)

**Comment by Redfiery** [comment]
Turned myself into a houseplant, funniest shit i've ever seen. 
![20210130151116_1](https://user-images.githubusercontent.com/78265850/106358814-c6be8a00-630e-11eb-90c4-c701039ca5c8.jpg)

**Comment by Demidevimon** [comment]
Having the same issue with the plant XD
![yR6grON](https://user-images.githubusercontent.com/50336681/107060411-edfcd780-67a4-11eb-8b9d-cc9b099e2bd2.jpg)

**Comment by ArcPh1r3** [comment]
the plant was intended and funny but was fixed a long time ago(and it was literally just the plant, not a lot of items)
