### ISSUE TITLE
Please make Lunar Shards usable

### ISSUE THREAD

**Issue by Jz1207** [ArcPh1r3/PaladinMod#23]
Literally all they need is minor tracking so they can actually hit anything, the tiny damage is meant to be balanced out by hitting many times but they barely hit with the travel time, tiny projectile size, barely visible reticle, and actually being aimed below the reticle. Thank you.

**Comment by BrokenDoop** [comment]
True, it's really underpowered with how it is right now, not worth using over the other abilities. 
Also really wish we had that Berserk skin...
