### ISSUE TITLE
Compatibility with ExtendedLoadout mod

### ISSUE THREAD

**Issue by HASJ** [ArcPh1r3/PaladinMod#3]
ExtendedLoadout allows you to choose a second set of skills but it is not working with the Paladin.
The extra skill slots don't show up on the character selection screen.

I am not sure which mod is creating the issue but ExtendLoadout works with other mod characters. I'll ask the ExtendedLoadout mod maker about it as well.

Thanks for the mod. It's up there with the best char mods ever made for the game.

**Comment by ArcPh1r3** [comment]
not sure if this is still an issue or what's required to get it working, but i should look into it sometime

**Comment by TheTimeSweeper** [comment]
greetings from over a year in the future. been playing with it and it works so gonna close it c:
