### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by GalacticRuler** [ArcPh1r3/PaladinMod#4]
getting extreme error spam consisting of:
`[Error  : Unity Log] MissingFieldException: Field 'RoR2.CharacterBody.bodyIndex' not found.
Stack trace:
DMD<>?1867651840.Hook<RoR2.UI.SkillIcon::Update>?38093312 (RoR2.UI.SkillIcon ) (at <fe2023f4a169403db128c18150497a67>:IL_0014)
`

character skill icons, cooldowns, descriptions, etc, are all broken as well. For all characters.

**Comment by GalacticRuler** [comment]
this might actually be caused by Heretic Selection actually.

**Comment by piratefinn** [comment]
Does it work with this installed? I know a major error stopped for me upon installing it due to a R2API & EnigmaticThunder clash https://thunderstore.io/package/XoXFaby/MMHOOK_Standalone/

**Comment by GalacticRuler** [comment]
yeah I have that
and the mod does work, but the error spam is insane; and it does still suffer from those listed bugs

**Comment by ArcPh1r3** [comment]
unrelated
