### ISSUE TITLE
Gold Items Not Functioning Conflict (MysticsItems, ClassicItems) (ShareSuite)

### ISSUE THREAD

**Issue by imakunee** [ArcPh1r3/PaladinMod#5]
When playing as Paladin, various gold changing items such as Piggy Bank (gives money over time gradually, from Classic Items) and/or Scratch Ticket (refunds final use of Shrine of Chance, from Mystics Items) do nothing to modify your gold amount. Some other users posted issues on the Classic Items page and that creator responded that it may be due to an issue involving object structures of the offending modded characters as only some modded characters experience the issue and vanilla characters work fine (https://github.com/ThinkInvis/RoR2-ClassicItems/issues/72#issuecomment-758110158). Thank you for your time on this mod, I greatly enjoy playing as the Paladin and look forward to a fix from whichever mods needed it.

Edit: Turns out it's ShareSuite. Creator said custom characters have to use ShareSuite's custom code for shared pools. >.> I'll just leave this open so you can make a statement for others investigating the same issue.

**Comment by ArcPh1r3** [comment]
having looked into the issue i found nothing that could possibly lead to incompatibility, and i've got no interest in spending more time on it
